package kz.railways.rbrestapp.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

import kz.railways.rbrestapp.entity.NarushBezopBigData;

public interface NarushBezopBigRepository extends CrudRepository<NarushBezopBigData, String> {

	@Query(value="select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS b_dt, concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.defects_id,d.title AS def_title,cl.title,cl.id as clid,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code, f.code AS farm_code,rb_dn.title AS nod_title from 	rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id"
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title"
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null "
			+ " ", nativeQuery = true)
	List<NarushBezopBigData> findAll(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod);
	
	@Query(value="select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS b_dt, concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.defects_id,d.title AS def_title,cl.title,cl.id as clid,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code AS farm_code,rb_dn.title AS nod_title from 	rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and cl.id = :cl "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and cl.id = :cl "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and cl.id = :cl ", nativeQuery = true)
	List<NarushBezopBigData> findByCl(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("cl") int cl);
	
	@Query(value="select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS b_dt, concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.defects_id,d.title AS def_title,cl.title,cl.id as clid,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code AS farm_code,rb_dn.title AS nod_title from 	rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and cl.id = :cl and "
			+ "	sf.struktura_id = :st "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and cl.id = :cl and "
			+ "	sf.struktura_id = :st "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and cl.id = :cl and "
			+ "	sf.struktura_id = :st ", nativeQuery = true)
	List<NarushBezopBigData> findByClAndStruct(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("cl") int cl, @Param("st") String st);
	
	@Query(value="select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS b_dt, concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.defects_id,d.title AS def_title,cl.title,cl.id as clid,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code AS farm_code,rb_dn.title AS nod_title from 	rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ " LEFT JOIN rb_struktura_farm sf ON sf.farm_id = f.id "			
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND sf.struktura_id = :farm "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ " LEFT JOIN rb_struktura_farm sf ON sf.farm_id = f.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND sf.struktura_id = :farm "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id " 
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ " LEFT JOIN rb_struktura_farm sf ON sf.farm_id = f.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND sf.struktura_id = :farm ", nativeQuery = true)
	List<NarushBezopBigData> findByFarm(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("farm") int farm);
	
	@Query(value="select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS b_dt, concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.defects_id,d.title AS def_title,cl.title,cl.id as clid,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code AS farm_code,rb_dn.title AS nod_title from 	rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND month(ind.date) = :m "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id " 
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND month(ind.date) = :m "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND month(ind.date) = :m "
			+ " ", nativeQuery = true)
	List<NarushBezopBigData> findByMonth(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("m") String m);
	
	@Query(value="select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS b_dt, concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.defects_id,d.title AS def_title,cl.title,cl.id as clid,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code AS farm_code,rb_dn.title AS nod_title from 	rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id"
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND month(ind.date) = :m and "
			+ "	sf.struktura_id = :st "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND month(ind.date) = :m and "
			+ "	sf.struktura_id = :st "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null AND month(ind.date) = :m and "
			+ "	sf.struktura_id = :st "
			+ " ", nativeQuery = true)
	List<NarushBezopBigData> findByMonthAndStruct(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("m") String m, @Param("st") String st);
	
	@Query(value="select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS b_dt, concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.defects_id,d.title AS def_title,cl.title,cl.id as clid,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code AS farm_code,rb_dn.title AS nod_title from 	rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and f.id = :hoz "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,ind.investigate,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,f.code,rb_dn.title from 	rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and f.id = :hoz "
			+ "	union all "
			+ "	select SUBSTR(ind.date, 1, 4) AS y1, concat(ind.date,\" \", ind.s_time) AS dt,concat(ind.e_date, \" \", ind.e_time) AS e_dt,ind.difficulties_id,d.title,cl.title,cl.id,ind.description,case "
			+ "						when f.sign_ds = 1 then rds.title "
			+ "						else ent.code "
			+ "					end as code,ent.code,f.code,rb_dn.title from 	rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_dn on rb_dn.id=ind.dn_id "
			+ " left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	left join rb_enterprises ent on ent.id=ind.enterprises_id "
			+ " left join rb_ds_station rds on f.sign_ds =1 and rds.id = ent.id "
			+ "	where ind.dn_id=:nod and (ind.date>=:b_date and ind.date<=:e_date) and f.own=1 and ind.deleted_at is null and f.id = :hoz ", nativeQuery = true)
	List<NarushBezopBigData> findByHoz(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("hoz") int hoz);
}
