package kz.railways.rbrestapp.repository;

import java.util.List;

import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.CrudRepository;
import org.springframework.data.repository.query.Param;

import kz.railways.rbrestapp.entity.NarushBezop;

public interface NarushBezopRepository extends CrudRepository<NarushBezop, Integer> {

	@Query(value="SELECT y, title, SUM(c) AS s FROM (select year(ind.date) AS Y, cl.title, count(*) AS c from rb_in_defects ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_defects d on d.id=ind.defects_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own=1   and ind.deleted_at  is  null and  ind.dn_id=:nod and ind.deleted_at is null "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_difficulties ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own=1   and ind.deleted_at  is  null and  ind.dn_id=:nod and ind.deleted_at is null  "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_other_difficulties ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own=1  and ind.deleted_at  is  null  and  ind.dn_id=:nod and ind.deleted_at is null "
			+ "group by 1,2 "
			+ "order BY 2) a GROUP BY title", nativeQuery = true)
	List<NarushBezop> findAll(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod);
		
	@Query(value="SELECT y, title, SUM(c) AS s FROM (select year(ind.date) AS Y, cl.title, count(*) AS c from rb_in_defects ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "left join rb_defects d on d.id=ind.defects_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own=1   and ind.deleted_at  is  null and  ind.dn_id=:nod and ind.deleted_at is null and "
			+ "sf.struktura_id = :st "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_difficulties ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own=1   and ind.deleted_at  is  null and  ind.dn_id=:nod and ind.deleted_at is null and "
			+ "sf.struktura_id = :st "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_other_difficulties ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own=1  and ind.deleted_at  is  null  and  ind.dn_id=:nod and ind.deleted_at is null and "
			+ "sf.struktura_id = :st "
			+ "group by 1,2 "
			+ "order BY 2) a GROUP BY title", nativeQuery = true)
	List<NarushBezop> findAllByStruct(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("st") String st);
	
	@Query(value="SELECT y, title, SUM(c) AS s FROM (select year(ind.date) AS Y, cl.title, count(*) AS c from rb_in_defects ind "
			+ "left join rb_farm f on f.id = ind.farm_id "
			+ "left join rb_defects d on d.id = ind.defects_id "
			+ "left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own in (0,1) and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_difficulties ind "
			+ "left join rb_farm f on f.id = ind.farm_id "
			+ "left join rb_difficulties d on d.id = ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own in (0,1) and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_other_difficulties ind "
			+ "left join rb_farm f on f.id = ind.farm_id "
			+ "left join rb_difficulties d on d.id = ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own in (0,1) and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "group by 1,2 "
			+ "order BY 2) a GROUP BY title", nativeQuery = true)
	List<NarushBezop> findAllWithoutNod(@Param("b_date") String b_date, @Param("e_date") String e_date);
	
	@Query(value="SELECT y, title, SUM(c) AS s FROM (select year(ind.date) AS Y, cl.title, count(*) AS c from rb_in_defects ind "
			+ "left join rb_farm f on f.id = ind.farm_id "
			+ "left join rb_defects d on d.id = ind.defects_id "
			+ "left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own = :own and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "group by 1,2 "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_difficulties ind "
			+ "left join rb_farm f on f.id = ind.farm_id "
			+ "left join rb_difficulties d on d.id = ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own = :own and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "group by 1,2 "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_other_difficulties ind "
			+ "left join rb_farm f on f.id = ind.farm_id "
			+ "left join rb_difficulties d on d.id = ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own = :own and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "group by 1,2 "
			+ "order BY 2) a GROUP BY title", nativeQuery = true)
	List<NarushBezop> findCompNOther(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("own") int own);
	
	@Query(value="SELECT y, title, SUM(c) AS s FROM (select year(ind.date) AS Y, cl.title, count(*) AS c from rb_in_defects ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "left join rb_defects d on d.id=ind.defects_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own in (1) and ind.deleted_at  is  null and  ind.dn_id=:nod and ind.deleted_at is null and "
			+ "sf.struktura_id = :st "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_difficulties ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own in (1) and ind.deleted_at  is  null and  ind.dn_id=:nod and ind.deleted_at is null and "
			+ "sf.struktura_id = :st "
			+ "group by 1,2 "
			+ " "
			+ "union all "
			+ "select year(ind.date),cl.title,count(*) from rb_in_other_difficulties ind "
			+ "left join rb_farm f on f.id=ind.farm_id "
			+ "left join rb_struktura_farm sf on sf.farm_id=f.id "
			+ "left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "where  (ind.date>=:b_date and ind.date<=:e_date) and f.own in (1) and ind.deleted_at  is  null  and  ind.dn_id=:nod and ind.deleted_at is null and "
			+ "sf.struktura_id = :st "
			+ "group by 1,2 "
			+ "order BY 2) a GROUP BY title", nativeQuery = true)
	List<NarushBezop> findNbdAllByStruct(@Param("b_date") String b_date, @Param("e_date") String e_date, @Param("nod") String nod, @Param("st") String st);
	/*@Query(value="SELECT a.title, a.y AS curryear, a.s AS currcount, b.y AS lastyear, b.lastcount  FROM (SELECT y, title, id, SUM(c) AS s FROM (select year(ind.date) AS Y, cl.title, cl.id, count(*) AS c from rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	where   "
			+ "		ind.date:b_date and ind.date <= :e_date and  "
			+ "		f.own=1 and  "
			+ "		ind.deleted_at is null and   "
			+ "		ind.dn_id = :nod and  "
			+ "		ind.deleted_at is null "
			+ "	group by 1,2 "
			+ "union all "
			+ "select year(ind.date),cl.title,cl.id, count(*) from rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	WHERE   "
			+ "		ind.date>=:b_date and ind.date <= :e_date and  "
			+ "		f.own=1 and  "
			+ "		ind.deleted_at is null and   "
			+ "		ind.dn_id = :nod and  "
			+ "		ind.deleted_at is null  "
			+ "	group by 1,2 "
			+ "union all "
			+ "select year(ind.date),cl.title,cl.id, count(*) from rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	where   "
			+ "		ind.date:b_date and ind.date <= :e_date and  "
			+ "		f.own=1  and  "
			+ "		ind.deleted_at  is  null  and   "
			+ "		ind.dn_id = :nod and  "
			+ "		ind.deleted_at is null "
			+ "	group by 1,2 "
			+ "	order by 2) a GROUP BY title) a "
			+ "	left JOIN (SELECT y, title, id, SUM(c) AS lastcount FROM (select year(ind.date) AS Y, cl.title, cl.id, count(*) AS c from rb_in_defects ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_defects d on d.id=ind.defects_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	where   "
			+ "		ind.date >= :last_b_date and ind.date <= :last_e_date and  "
			+ "		f.own=1 and  "
			+ "		ind.deleted_at is null and   "
			+ "		ind.dn_id = :nod and  "
			+ "		ind.deleted_at is null "
			+ "	group by 1,2 "
			+ "union all "
			+ "select year(ind.date),cl.title,cl.id, count(*) from rb_in_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	WHERE   "
			+ "		ind.date>=:last_b_date and ind.date <= :last_e_date and  "
			+ "		f.own=1 and  "
			+ "		ind.deleted_at is null and   "
			+ "		ind.dn_id = :nod and  "
			+ "		ind.deleted_at is null  "
			+ "	group by 1,2 "
			+ "union all "
			+ "select year(ind.date),cl.title,cl.id, count(*) from rb_in_other_difficulties ind "
			+ "	left join rb_farm f on f.id=ind.farm_id "
			+ "	left join rb_difficulties d on d.id=ind.difficulties_id "
			+ "	left join rb_classifiers cl on cl.id=d.classifiers_id "
			+ "	where   "
			+ "		ind.date >= :last_b_date and ind.date <= :last_e_date and  "
			+ "		f.own=1  and  "
			+ "		ind.deleted_at  is  null  and   "
			+ "		ind.dn_id = :nod and  "
			+ "		ind.deleted_at is null "
			+ "	group by 1,2 "
			+ "	order by 2) a GROUP BY title) b ON a.id = b.id ", nativeQuery = true)
	List<NarushBezop2> findAll2(@Param("last_b_date") String last_b_date, 
			@Param("last_e_date") String last_e_date, 
			@Param("b_date") String b_date, 
			@Param("e_date") String e_date, 
			@Param("nod") String nod);*/
	
	@Query(value="SELECT y, title, SUM(c) AS s FROM (select year(ind.date) AS Y, d.title, count(*) AS c from rb_in_defects ind "
			+ "			left join rb_farm f on f.id = ind.farm_id "
			+ "			left join rb_defects d on d.id = ind.defects_id "
			+ "			left join rb_classifiers cl on cl.id = d.classifiers_id 			"
			+ "			where  (ind.date>=:b_date and ind.date<=:e_date) and f.own = 1 and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "			group by 1,2 "
			+ "			union all "
			+ "			select year(ind.date),d.title,count(*) from rb_in_difficulties ind "
			+ "			left join rb_farm f on f.id = ind.farm_id "
			+ "			left join rb_difficulties d on d.id = ind.difficulties_id "
			+ "			left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "			where  (ind.date>=:b_date and ind.date<=:e_date) and f.own = 1 and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "			group by 1,2 "
			+ "			union all "
			+ "			select year(ind.date),d.title,count(*) from rb_in_other_difficulties ind "
			+ "			left join rb_farm f on f.id = ind.farm_id "
			+ "			left join rb_difficulties d on d.id = ind.difficulties_id "
			+ "			left join rb_classifiers cl on cl.id = d.classifiers_id "
			+ "			where  (ind.date>=:b_date and ind.date<=:e_date) and f.own = 1 and ind.deleted_at is null and ind.deleted_at is null and d.classifiers_id in (1,2,3,4) "
			+ "			group by 1,2 "
			+ "			order BY 2) a GROUP BY title order by s desc", nativeQuery = true)
	List<NarushBezop> findRazrezNbd(@Param("b_date") String b_date, @Param("e_date") String e_date);
	
}
