spring:  
    datasource:
      url: jdbc:mysql://10.99.2.129/ispb 
      username: nagmetkaliev_k
      password: HG#F39728;df
    jpa:      
      hibernate:
        ddl-auto: none
server:
  port: 6791